---
apiVersion: v1
kind: Namespace
metadata:
  name: metrics-scraper
  labels:
    name: metrics-scraper
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metrics-role
rules:
  - nonResourceURLs: ["/metrics"]
    verbs: ["get"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metrics-scraper-sa
  namespace: metrics-scraper
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metrics-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: metrics-role
subjects:
  - kind: ServiceAccount
    name: metrics-scraper-sa
    namespace: metrics-scraper
---
apiVersion: v1
kind: Pod
metadata:
  name: metrics-scraper
  namespace: metrics-scraper
spec:
  serviceAccount: metrics-scraper-sa
  containers:
    - command:
        - tail
        - -f
        - /dev/null
      image: alpine/curl
      name: metrics-scraper
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always