---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: self-signed-ca-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pink-ca-certificate
  namespace: test
spec:
  secretName: pink-ca-secret
  dnsNames:
    - "pink.butterfly-np.com"
  issuerRef:
    name: self-signed-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prometheus-ca-certificate
  namespace: monitoring
spec:
  secretName: prometheus-ca-secret
  dnsNames:
    - "prometheus.butterfly-np.com"
  issuerRef:
    name: self-signed-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: alertmanager-ca-certificate
  namespace: monitoring
spec:
  secretName: alertmanager-ca-secret
  dnsNames:
    - "alertmanager.butterfly-np.com"
  issuerRef:
    name: self-signed-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-ca-certificate
  namespace: monitoring
spec:
  secretName: grafana-ca-secret
  dnsNames:
    - "grafana.butterfly-np.com"
  issuerRef:
    name: self-signed-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io